// include/version.h
// (Autogenerated from cmake/version.h.in)
#pragma once

#define PROJECT_NAME "cmake_project_template"
#define PROJECT_VERSION_MAJOR "1"
#define PROJECT_VERSION_MINOR "0"
#define PROJECT_VERSION_PATCH "0"
#define PROJECT_VERSION "1.0.0"
